"""empty message

Revision ID: 459b4dc9ae45
Revises: 19c21ef696da
Create Date: 2019-10-30 20:49:17.036131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459b4dc9ae45'
down_revision = '19c21ef696da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('airlines',
    sa.Column('iata', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('iata')
    )
    op.create_table('airports',
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('city', sa.String(length=75), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('time_zone', sa.String(length=60), nullable=False),
    sa.Column('dst', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('iata')
    )
    op.create_table('trips',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('trip_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['address.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('flights',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=True),
    sa.Column('flight_num', sa.Integer(), nullable=True),
    sa.Column('depart_iata', sa.String(length=3), nullable=False),
    sa.Column('arrival_iata', sa.String(length=3), nullable=False),
    sa.Column('depart_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_iata'], ['airlines.iata'], ),
    sa.ForeignKeyConstraint(['arrival_iata'], ['airports.iata'], ),
    sa.ForeignKeyConstraint(['depart_iata'], ['airports.iata'], ),
    sa.ForeignKeyConstraint(['tid'], ['trips.tid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), nullable=False),
    sa.Column('public', sa.BOOLEAN(), nullable=False),
    sa.CheckConstraint('public IN (0, 1)'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('flights')
    op.drop_table('trips')
    op.drop_table('airports')
    op.drop_table('airlines')
    op.drop_table('address')
    # ### end Alembic commands ###
