"""empty message

Revision ID: ed060304bba1
Revises:
Create Date: 2019-11-13 21:29:19.470099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed060304bba1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('iata', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('iata')
    )
    op.create_table('airports',
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('city', sa.String(length=75), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('time_zone', sa.String(length=60), nullable=False),
    sa.Column('dst', sa.String(length=1), nullable=False),
    # sa.CheckConstraint("dst IN ('E', 'A', 'S', 'O', 'Z', 'N', 'U')"),
    # sa.CheckConstraint('latitude >= -90 AND latitude <= 90'),
    # sa.CheckConstraint('longitude >= -180 AND longitude <= 180'),
    sa.PrimaryKeyConstraint('iata')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.CheckConstraint("email LIKE '%_@_%._%'"),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trips',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('trip_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('details',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['iata'], ['airports.iata'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tid'], ['trips.tid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('flights',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=True),
    sa.Column('flight_num', sa.Integer(), nullable=True),
    sa.Column('depart_iata', sa.String(length=3), nullable=False),
    sa.Column('arrival_iata', sa.String(length=3), nullable=False),
    sa.Column('depart_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration > 0'),
    sa.CheckConstraint('flight_num > 0'),
    sa.CheckConstraint('mileage > 0'),
    sa.ForeignKeyConstraint(['airline_iata'], ['airlines.iata'], ),
    sa.ForeignKeyConstraint(['arrival_iata'], ['airports.iata'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depart_iata'], ['airports.iata'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tid'], ['trips.tid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('details')
    op.drop_table('trips')
    op.drop_table('user')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
